version: '3.8'
services:
  app:
    build: .
    restart: always
    ports:
      - "3005:3005"
    volumes:
      - uploaded_videos:/app/public/videos
      - uploaded_thumbnails:/app/public/thumbnails
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/margotv
      - PORT=3005
    depends_on:
      - mongodb
    networks:
      - margotv-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3005"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb_data:/data/db
    networks:
      - margotv-network
    command: mongod --bind_ip_all

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - nginx_logs:/var/log/nginx
    depends_on:
      - app
    networks:
      - margotv-network

networks:
  margotv-network:
    driver: bridge

volumes:
  mongodb_data:
  uploaded_videos:
  uploaded_thumbnails:
  nginx_logs: 